Resources:
  CarTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.carsTable}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: brand
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: brand
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}